### ISSUE TITLE
Referees - Add feedbacks

### ISSUE THREAD

**Issue by GatienH** [GatienH/gm-stagging#19]
- [x] 2 bandes de 4 logos
- [x] défilement infini
- [x] de dte > gche / de gche > dte
- [x] stop l'anim au hover
- [x] lien vers la page customers

sources : https://css-tricks.com/infinite-all-css-scrolling-slideshow/

**Comment by GatienH** [comment]
https://css-tricks.com/infinite-all-css-scrolling-slideshow/

**Comment by GatienH** [comment]
stop l'anim au hover 

```css
.referees-list:hover div {
  animation-play-state: paused
}
```
