### ISSUE TITLE
Mobile - fix hover and onclicks behaviours

### ISSUE THREAD

**Issue by GatienH** [GatienH/gm-stagging#31]
When back to previous page : 

- [ ] btn shouldn't be green
- [x] logos shouldn't be paused

**Comment by GatienH** [comment]
Logos issue fixed by #39

**Comment by GatienH** [comment]
Not a bug but a feature.

If needed for btn : remove focus effect

```css
.btn a:focus .btn-bg {
  fill:none;
}

.btn a:focus .btn-gap {
  stroke:none;
}
```
